In [1]:
import numpy as np
import pandas as pd

In [3]:
flats = pd.read_csv('../dataset/flats_cleaned.csv')
houses = pd.read_csv('../dataset/house_cleaned.csv')

In [4]:
df = pd.concat([flats,houses],ignore_index=True)

In [5]:
df = df.sample(df.shape[0],ignore_index=True)

In [6]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 88A Gurgaon,flat,the center court,2.10,12173.0,1725.0,Super Built up area 2175(202.06 sq.m.)Built Up...,4,4,3,"study room,servant room","Tower T2 C003, Sector 88A Gurgaon, Gurgaon, Ha...",0.0,East,Within 6 months,"['Elan Miracle Mall', 'Dwarka Expy, Harsaru', ...",Ashiana landcraft the center court is a reside...,NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
1,3 BHK Flat in Sector 89 Gurgaon,flat,smart world gems,1.20,12526.0,958.0,Carpet area: 958 (89 sq.m.),3,3,3,"pooja room,store room","N54c, Sector 89 Gurgaon, Gurgaon, Haryana",3.0,East,Oct 2023,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",Corner unit near biggest green area of the pro...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...","['Security / Fire Alarm', 'Private Garden / Te...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,3 BHK Flat in Sector 88A Gurgaon,flat,godrej icon,1.65,9041.0,1825.0,Super Built up area 1825(169.55 sq.m.),3,3,3,not available,"1204, Sector 88A Gurgaon, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['JMS Crosswalk', ""Saint Paul's School"", 'Indu...",Gurgaon is india's second largest information ...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...",NaN
3,1 BHK Flat in Sector 83 Gurgaon,flat,sapphire eighty three,0.65,9286.0,700.0,Built Up area: 700 (65.03 sq.m.),1,1,0,not available,"Sector 83, Sector 83 Gurgaon, Gurgaon, Haryana",6.0,NaN,undefined,"['S.R.S. Hospital and Critical Care Unit', 'Or...",1bhk multistorey apartment for resale in sapph...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Safety5 out of 5', 'Lifestyle5 out of 5', 'E..."
4,3 BHK Flat in Sector 15 Gurgaon,flat,park view apartments,1.60,11034.0,1450.0,Carpet area: 1450 (134.71 sq.m.),3,3,3+,pooja room,"Sector 15 Gurgaon, Gurgaon, Haryana",2.0,North-West,5 to 10 Year Old,"['Hanuman Mandir', 'Rajiv Chowk Mosque', 'Hdfc...",A property at the prime location of gurugram w...,"['6 Fan', '10 Light', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4.5 out of 5', 'Lifestyle4 out of..."

In [7]:
df.to_csv('gurgaon_properties.csv',index=False)